package app.knotwork.android.domain.engine.executors

import app.knotwork.android.domain.constants.DefaultPrompts
import app.knotwork.android.domain.constants.PipelineExecutionDefaults
import app.knotwork.android.domain.engine.LlmInferenceEngine
import app.knotwork.android.domain.models.AgentOrchestratorState
import app.knotwork.android.domain.models.ExecutionScope
import app.knotwork.android.domain.models.NodeExecutionResult
import app.knotwork.android.domain.models.NodeModel
import app.knotwork.android.domain.models.NodeOutput
import app.knotwork.android.domain.models.NodeType
import app.knotwork.android.domain.models.Result
import app.knotwork.android.domain.repositories.ChatRepository
import app.knotwork.android.domain.usecases.LoadModelUseCase
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import timber.log.Timber
import javax.inject.Inject

/**
 * Executor shared by the three "system reasoning" node types — [NodeType.INTENT_ROUTER],
 * [NodeType.DECOMPOSITION], and [NodeType.EVALUATION].
 *
 * They all share the same shape: run the local model with the node's `systemPrompt`
 * (or the matching [DefaultPrompts.System.SYSTEM_FALLBACK]) over the upstream context
 * `inputText`, stream tokens as orchestrator state, and emit the final response. The only
 * type-specific behaviour is that for [NodeType.INTENT_ROUTER] the executor also exposes
 * the response as the [NodeExecutionResult.routingKey][app.knotwork.android.domain.models.NodeExecutionResult.routingKey]
 * so that `GraphExecutionEngine` can resolve the next labelled connection.
 */
class SystemNodeExecutor @Inject constructor(
    private val llmEngine: LlmInferenceEngine,
    private val loadModelUseCase: LoadModelUseCase,
    private val chatRepository: ChatRepository,
) : NodeExecutor {

    override fun execute(
        node: NodeModel,
        inputText: String,
        sessionId: String,
        originalPrompt: String,
        runId: String?,
        scope: ExecutionScope,
    ): Flow<NodeOutput> = flow {
        val nodeSystemPrompt = node.systemPrompt ?: DefaultPrompts.System.SYSTEM_FALLBACK
        val fullPrompt = "$nodeSystemPrompt\n\nUSER: $inputText\nAGENT: "

        val loadResult = loadModelUseCase(node.modelPath)
        if (loadResult is Result.Error) {
            val errorMsg = "Error loading local model for system node"
            emit(NodeOutput.State(AgentOrchestratorState.Error(errorMsg)))
            emit(NodeOutput.Result(NodeExecutionResult(error = errorMsg)))
            return@flow
        }

        val responseStream = llmEngine.generateResponseStream(fullPrompt)
        val accumulatedResponse = StringBuilder()

        try {
            responseStream.collect { token ->
                accumulatedResponse.append(token)
                emit(NodeOutput.State(AgentOrchestratorState.Thinking(accumulatedResponse.toString())))
            }
        } catch (e: CancellationException) {
            // Preserve structured-concurrency cancellation: a broad `catch (Exception)`
            // would silently swallow cancellation and leave the parent coroutine running.
            throw e
        } catch (e: Exception) {
            Timber.tag(
                "PipelineDebug",
            ).e(e, "[NODE_ERR] type=${node.type.name} id=${node.id} error in SystemNodeExecutor generation")
            emit(NodeOutput.State(AgentOrchestratorState.Error(e.message ?: "Unknown error")))
            emit(NodeOutput.Result(NodeExecutionResult(error = e.message)))
            return@flow
        }

        val generatedText = accumulatedResponse.toString().trim()
        val fullResponseText = if (generatedText.isNotEmpty()) generatedText else "No response generated by model."
        // INTENT_ROUTER exposes the whole response as the routing key (matched
        // against class-named edges). EVALUATION distils the response to a
        // Pass / Retry / Fail verdict so the engine can route to the matching
        // output port; a null verdict (no recognisable token) lets the engine
        // fall back to the first outgoing edge.
        val routingKey = when (node.type) {
            NodeType.INTENT_ROUTER -> fullResponseText
            NodeType.EVALUATION -> parseEvaluationVerdict(fullResponseText)
            else -> null
        }

        kotlinx.coroutines.delay(PipelineExecutionDefaults.NODE_RESULT_EMIT_DELAY_MS)

        emit(NodeOutput.Result(NodeExecutionResult(outputText = fullResponseText, routingKey = routingKey)))
    }

    /**
     * Extracts the Pass / Retry / Fail verdict from an [NodeType.EVALUATION]
     * response. Returns the canonical edge-label form (`"Pass"` / `"Retry"` /
     * `"Fail"`) of the first verdict token found, or `null` when none is
     * present so the engine routes to the first outgoing edge as a fallback.
     *
     * @param response The model's full evaluation reply.
     * @return The matching [app.knotwork.android.domain.models.NodeType.EVALUATION]
     *   output-port label, or `null` when the response carries no verdict token.
     */
    private fun parseEvaluationVerdict(response: String): String? {
        val match = EVALUATION_VERDICT_REGEX.find(response) ?: return null
        return when (match.value.uppercase()) {
            "PASS" -> "Pass"
            "RETRY" -> "Retry"
            else -> "Fail"
        }
    }

    private companion object {
        /**
         * Matches the first standalone PASS / RETRY / FAIL token (word
         * boundaries, case-insensitive) in an evaluation response.
         */
        val EVALUATION_VERDICT_REGEX = Regex("""\b(PASS|RETRY|FAIL)\b""", RegexOption.IGNORE_CASE)
    }
}
