package app.knotwork.android.domain.models

/**
 * Persistent record of one human-in-the-loop interaction a parked run is
 * waiting on.
 *
 * Created when the live in-process waiting phase of a HITL gate (tool
 * approval or clarification question) times out and the run transitions into
 * its persistent waiting phase: the engine coroutine ends, the foreground
 * service is released, and this record — together with the run record's
 * `WAITING_APPROVAL` / `WAITING_CLARIFICATION` status — is what survives
 * process death and lets the user answer hours later from a notification or
 * by reopening the chat.
 *
 * The record is strictly one-shot: the user's response ([decision] or
 * [answer]) is written onto it before the run is resumed, and the resumed
 * node executor consumes the record (deletes it) exactly once. Binding the
 * response to the recorded request snapshot ([toolName] + [toolArgs]) is the
 * TOCTOU guard — if the re-executed node resolves different arguments, the
 * stale response must not authorise them and a fresh approval is raised.
 *
 * @property runId Id of the parked pipeline run; primary key — a run waits on
 *   at most one interaction at a time.
 * @property sessionId Id of the owning chat session, for session-scoped UI
 *   lookup on reattach.
 * @property kind Which HITL gate the run is parked on. See [PendingInteractionKind].
 * @property toolName Name of the tool awaiting approval; `null` for
 *   clarification records.
 * @property toolArgs JSON argument string of the tool call awaiting approval,
 *   exactly as resolved when the gate was raised; `null` for clarification
 *   records.
 * @property risk Risk classification of the tool awaiting approval; `null`
 *   for clarification records.
 * @property question The clarifying question generated by the LLM; persisted
 *   so resume can re-render it without re-running inference. `null` for
 *   approval records.
 * @property options Optional answer choices of the clarifying question;
 *   `null` for approval records or free-form questions.
 * @property decision The user's approval decision recorded after the park;
 *   `null` while the interaction is still unanswered. See [PendingDecision].
 * @property answer The user's clarification answer recorded after the park;
 *   `null` while unanswered.
 * @property requestedAt Epoch millis when the persistent waiting phase began.
 *   The background approval window (`backgroundApprovalWindowHours` setting)
 *   counts from this moment.
 */
data class PendingInteraction(
    val runId: String,
    val sessionId: String,
    val kind: PendingInteractionKind,
    val toolName: String? = null,
    val toolArgs: String? = null,
    val risk: ToolRisk? = null,
    val question: String? = null,
    val options: List<String>? = null,
    val decision: PendingDecision? = null,
    val answer: String? = null,
    val requestedAt: Long,
)

/**
 * The HITL gate a [PendingInteraction] is parked on.
 */
enum class PendingInteractionKind {
    /** The run waits for the user to approve or deny a staged tool call. */
    APPROVAL,

    /** The run waits for the user to answer a clarifying question. */
    CLARIFICATION,
}

/**
 * The user's recorded response to a parked approval request.
 *
 * Recorded onto the [PendingInteraction] before the run is resumed; the
 * resumed tool node consumes it one-shot, subject to the TOCTOU argument
 * match (see [PendingInteraction]).
 */
enum class PendingDecision {
    /** The user approved the staged tool call. */
    APPROVED,

    /** The user denied the staged tool call. */
    DENIED,
}
