package ai.agent.android.domain.repositories

import ai.agent.android.domain.models.ChatMessage
import ai.agent.android.domain.models.ChatSession
import kotlinx.coroutines.flow.Flow

/**
 * Repository interface for managing chat history and sessions.
 */
interface ChatRepository {
    /**
     * Saves a new chat message.
     *
     * @param message The [ChatMessage] to save.
     */
    suspend fun saveMessage(message: ChatMessage)

    /**
     * Retrieves the history of messages for a given session.
     *
     * @param sessionId The unique ID of the chat session.
     * @return A [Flow] emitting the list of [ChatMessage] ordered by time.
     */
    fun getMessagesForSession(sessionId: String): Flow<List<ChatMessage>>

    /**
     * Deletes all messages associated with the given session, and the session itself.
     *
     * @param sessionId The unique ID of the chat session to delete.
     */
    suspend fun deleteSession(sessionId: String)

    /**
     * Retrieves a list of all distinct chat session IDs.
     * Deprecated: Use getSessionsFlow() instead.
     *
     * @return A list of unique session IDs.
     */
    suspend fun getAllSessions(): List<String>

    /**
     * Deletes a specific chat message by its ID.
     *
     * @param messageId The ID of the message to delete.
     */
    suspend fun deleteMessage(messageId: Long)

    /**
     * Retrieves recent system messages (logs/observations).
     *
     * @param limit The maximum number of messages to retrieve.
     * @return A [Flow] emitting a list of recent system [ChatMessage].
     */
    fun getRecentSystemMessages(limit: Int = 100): Flow<List<ChatMessage>>

    /**
     * Creates or updates a chat session.
     *
     * @param session The [ChatSession] to create or update.
     */
    suspend fun saveSession(session: ChatSession)

    /**
     * Retrieves all chat sessions as a flow, ordered by the last update time.
     *
     * @return A [Flow] emitting the list of [ChatSession].
     */
    fun getSessionsFlow(): Flow<List<ChatSession>>

    /**
     * Retrieves a specific chat session by its ID.
     *
     * @param id The ID of the session.
     * @return The [ChatSession] if found, null otherwise.
     */
    suspend fun getSessionById(id: String): ChatSession?

    /**
     * Saves a trace step for a session.
     *
     * @param sessionId The ID of the session.
     * @param nodeName The name of the node.
     * @param outputText The output text generated by the node.
     * @param durationMs Wall-clock time the node took to execute, in milliseconds.
     * @param tokenCount Approximate number of tokens produced by the node (LLM nodes only);
     *   `null` for nodes that do not consume or emit tokens.
     */
    suspend fun saveTraceStep(
        sessionId: String,
        nodeName: String,
        outputText: String,
        durationMs: Long,
        tokenCount: Int?,
    )

    /**
     * Retrieves trace steps for a given session.
     *
     * @param sessionId The ID of the session.
     * @return A [Flow] emitting the list of [ai.agent.android.domain.models.AgentOrchestratorState.TraceStep] ordered by time.
     */
    fun getTraceSteps(sessionId: String): Flow<List<ai.agent.android.domain.models.AgentOrchestratorState.TraceStep>>
}
