package app.knotwork.android.toolsprobe

import androidx.appfunctions.AppFunctionContext
import androidx.appfunctions.service.AppFunction

/**
 * Single-function AppFunction surface shipped by the `:tools-probe` debug app for the
 * Phase 20 end-to-end test harness.
 *
 * The class declares one `@AppFunction`: [echo], which returns its `message` argument
 * verbatim. Its sole purpose is to give the agent's caller-side path (`LocalAppFunctionManager`
 * → `ToolRepository.executeTool` → system `AppFunctionManager`) a deterministic remote
 * target installed on the device under test. The KSP processor generated by
 * `androidx.appfunctions:appfunctions-compiler` consumes the annotation to:
 *
 *  - emit the `app_functions.xml` (and v2) inventory under the APK's `assets/` so the
 *    platform discovery service can advertise the function to other apps;
 *  - generate dispatch infrastructure consumed by the auto-merged
 *    `androidx.appfunctions.service.PlatformAppFunctionService`, which is enabled by the
 *    library's manifest on API 36+ (see the AAR `values-v36/values-v36.xml`).
 *
 * The probe deliberately avoids declaring its own custom `AppFunctionService`: the
 * platform-provided merged service is sufficient and keeps the probe a pure data-plane
 * peer for the e2e test. The agent itself takes the same route — it relies on the merged
 * `PlatformAppFunctionService` plus `@AppFunction`-annotated wrappers (e.g.
 * `SearchAppFunction`) instead of subclassing `AppFunctionService`.
 *
 * The class is instantiated by the AppFunction runtime on each invocation; it must
 * therefore have a no-arg public constructor (see `AppFunctionConfiguration` if
 * dependency injection becomes necessary in the future).
 */
class EchoAppFunction {

    /**
     * Echoes the supplied [message] back unchanged so the caller-side e2e test can verify
     * the full round-trip path (JSON arguments → `AppFunctionData` → IPC → response →
     * decoded JSON) without depending on network access or any non-deterministic side
     * effect of a more realistic AppFunction.
     *
     * The leading [context] parameter is required by the AppFunctions framework: the KSP
     * compiler rejects `@AppFunction` declarations whose first parameter is not an
     * [AppFunctionContext]. The probe ignores it (no per-caller policy here), but keeping
     * the parameter satisfies the framework's contract.
     *
     * @param context Per-invocation context supplied by the AppFunctions runtime;
     *   intentionally unused — the probe is the most permissive AppFunction possible.
     * @param message Free-form text the caller wants reflected back. Empty strings are
     *   accepted to keep the surface symmetric with the platform contract (the value is
     *   carried as a typed `String` parameter; the AppFunction framework does not require
     *   non-blank inputs).
     * @return The exact value of [message]. Returning the input unchanged is what makes
     *   this function a useful e2e probe: the assertion in `AppFunctionsEndToEndTest`
     *   becomes `expected == actual` rather than a parser over an opaque payload.
     */
    @AppFunction
    @Suppress("UnusedParameter")
    suspend fun echo(context: AppFunctionContext, message: String): String = message
}
