package ai.agent.android.domain.engine.executors

import ai.agent.android.domain.engine.LlmInferenceEngine
import ai.agent.android.domain.models.AgentOrchestratorState
import ai.agent.android.domain.models.ChatMessage
import ai.agent.android.domain.models.NodeExecutionResult
import ai.agent.android.domain.models.NodeModel
import ai.agent.android.domain.models.NodeType
import ai.agent.android.domain.models.Result
import ai.agent.android.domain.models.Role
import ai.agent.android.domain.repositories.ChatRepository
import ai.agent.android.domain.usecases.LoadModelUseCase
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import timber.log.Timber
import javax.inject.Inject

class SystemNodeExecutor @Inject constructor(
    private val llmEngine: LlmInferenceEngine,
    private val loadModelUseCase: LoadModelUseCase,
    private val chatRepository: ChatRepository
) : NodeExecutor {

    override fun execute(
        node: NodeModel,
        inputText: String,
        sessionId: String,
        originalPrompt: String
    ): Flow<Any> = flow {
        val nodeSystemPrompt = node.systemPrompt ?: "You are an AI assistant."
        val fullPrompt = "$nodeSystemPrompt\n\nUSER: $inputText\nAGENT: "
        
        val loadResult = loadModelUseCase(node.modelPath)
        if (loadResult is Result.Error) {
            val errorMsg = "Error loading local model for system node"
            emit(AgentOrchestratorState.Error(errorMsg))
            emit(NodeExecutionResult(error = errorMsg))
            return@flow
        }

        val responseStream = llmEngine.generateResponseStream(fullPrompt)
        val accumulatedResponse = StringBuilder()
        
        try {
            responseStream.collect { token ->
                accumulatedResponse.append(token)
                emit(AgentOrchestratorState.Thinking(accumulatedResponse.toString()))
            }
        } catch (e: Exception) {
            Timber.e(e, "Error in SystemNodeExecutor generation")
            emit(AgentOrchestratorState.Error(e.message ?: "Unknown error"))
            emit(NodeExecutionResult(error = e.message))
            return@flow
        }
        
        val generatedText = accumulatedResponse.toString().trim()
        val fullResponseText = if (generatedText.isNotEmpty()) generatedText else "No response generated by model."
        val routingKey = if (node.type == NodeType.INTENT_ROUTER) fullResponseText else null
        
        kotlinx.coroutines.delay(1000)
        
        emit(NodeExecutionResult(outputText = fullResponseText, routingKey = routingKey))
    }
}