package ai.agent.android.domain.engine.executors

import ai.agent.android.domain.constants.DefaultPrompts
import ai.agent.android.domain.constants.PipelineExecutionDefaults
import ai.agent.android.domain.engine.LlmInferenceEngine
import ai.agent.android.domain.models.AgentOrchestratorState
import ai.agent.android.domain.models.NodeExecutionResult
import ai.agent.android.domain.models.NodeModel
import ai.agent.android.domain.models.NodeOutput
import ai.agent.android.domain.models.NodeType
import ai.agent.android.domain.models.Result
import ai.agent.android.domain.repositories.ChatRepository
import ai.agent.android.domain.usecases.LoadModelUseCase
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import timber.log.Timber
import javax.inject.Inject

/**
 * Executor shared by the three "system reasoning" node types — [NodeType.INTENT_ROUTER],
 * [NodeType.DECOMPOSITION], and [NodeType.EVALUATION].
 *
 * They all share the same shape: run the local model with the node's `systemPrompt`
 * (or the matching [DefaultPrompts.System.SYSTEM_FALLBACK]) over the upstream context
 * `inputText`, stream tokens as orchestrator state, and emit the final response. The only
 * type-specific behaviour is that for [NodeType.INTENT_ROUTER] the executor also exposes
 * the response as the [NodeExecutionResult.routingKey][ai.agent.android.domain.models.NodeExecutionResult.routingKey]
 * so that `GraphExecutionEngine` can resolve the next labelled connection.
 */
class SystemNodeExecutor @Inject constructor(
    private val llmEngine: LlmInferenceEngine,
    private val loadModelUseCase: LoadModelUseCase,
    private val chatRepository: ChatRepository,
) : NodeExecutor {

    override fun execute(
        node: NodeModel,
        inputText: String,
        sessionId: String,
        originalPrompt: String,
    ): Flow<NodeOutput> = flow {
        val nodeSystemPrompt = node.systemPrompt ?: DefaultPrompts.System.SYSTEM_FALLBACK
        val fullPrompt = "$nodeSystemPrompt\n\nUSER: $inputText\nAGENT: "

        val loadResult = loadModelUseCase(node.modelPath)
        if (loadResult is Result.Error) {
            val errorMsg = "Error loading local model for system node"
            emit(NodeOutput.State(AgentOrchestratorState.Error(errorMsg)))
            emit(NodeOutput.Result(NodeExecutionResult(error = errorMsg)))
            return@flow
        }

        val responseStream = llmEngine.generateResponseStream(fullPrompt)
        val accumulatedResponse = StringBuilder()

        try {
            responseStream.collect { token ->
                accumulatedResponse.append(token)
                emit(NodeOutput.State(AgentOrchestratorState.Thinking(accumulatedResponse.toString())))
            }
        } catch (e: CancellationException) {
            // Preserve structured-concurrency cancellation: a broad `catch (Exception)`
            // would silently swallow cancellation and leave the parent coroutine running.
            throw e
        } catch (e: Exception) {
            Timber.tag(
                "PipelineDebug",
            ).e(e, "[NODE_ERR] type=${node.type.name} id=${node.id} error in SystemNodeExecutor generation")
            emit(NodeOutput.State(AgentOrchestratorState.Error(e.message ?: "Unknown error")))
            emit(NodeOutput.Result(NodeExecutionResult(error = e.message)))
            return@flow
        }

        val generatedText = accumulatedResponse.toString().trim()
        val fullResponseText = if (generatedText.isNotEmpty()) generatedText else "No response generated by model."
        val routingKey = if (node.type == NodeType.INTENT_ROUTER) fullResponseText else null

        kotlinx.coroutines.delay(PipelineExecutionDefaults.NODE_RESULT_EMIT_DELAY_MS)

        emit(NodeOutput.Result(NodeExecutionResult(outputText = fullResponseText, routingKey = routingKey)))
    }
}
