package app.knotwork.android.data.local.dao

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.knotwork.android.data.local.AppDatabase
import app.knotwork.android.data.local.models.MemoryChunkEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented coverage for the SQL-bearing methods on [MemoryDao]. The
 * mocked unit tests in `MemoryRepositoryImplTest` can verify call routing
 * but cannot exercise the SQL — these tests run against an in-memory Room
 * database to lock the compaction / pinning semantics and the Flow-based
 * stat projections.
 */
@RunWith(AndroidJUnit4::class)
class MemoryDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var dao: MemoryDao

    @Before
    fun setup() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        dao = database.memoryDao()
    }

    @After
    fun teardown() {
        database.close()
    }

    @Test
    fun insertMemory_returnsAutoGeneratedRowId() = runBlocking {
        val id = dao.insertMemory(unpinned(text = "x", timestamp = 1L))
        assertTrue("Auto-generated id must be positive", id > 0L)
    }

    @Test
    fun deleteOldestMemories_keepsPinnedChunksRegardlessOfKeepLimit() = runBlocking {
        // Three unpinned rows + two pinned rows. With keepLimit = 1, the
        // compaction should leave 1 most-recent unpinned + both pinned = 3
        // rows total. Without the `isPinned = 0` guard the pinned rows would
        // be silently dropped because their ids fall outside the LIMIT 1
        // window.
        val oldestUnpinnedId = dao.insertMemory(unpinned(text = "u-old", timestamp = 100L))
        val midUnpinnedId = dao.insertMemory(unpinned(text = "u-mid", timestamp = 200L))
        val newestUnpinnedId = dao.insertMemory(unpinned(text = "u-new", timestamp = 300L))
        val pinnedOldId = dao.insertMemory(pinned(text = "p-old", timestamp = 50L))
        val pinnedRecentId = dao.insertMemory(pinned(text = "p-recent", timestamp = 250L))

        dao.deleteOldestMemories(keepLimit = 1)

        val survivors = dao.getAllMemories().associateBy { it.id }
        assertTrue("Pinned old chunk must survive", survivors.containsKey(pinnedOldId))
        assertTrue("Pinned recent chunk must survive", survivors.containsKey(pinnedRecentId))
        assertTrue("Most-recent unpinned must survive", survivors.containsKey(newestUnpinnedId))
        assertFalse("Older unpinned must be deleted", survivors.containsKey(midUnpinnedId))
        assertFalse("Oldest unpinned must be deleted", survivors.containsKey(oldestUnpinnedId))
        assertEquals(3, survivors.size)
    }

    @Test
    fun setMemoryPinned_flipsFlagOnSingleRow() = runBlocking {
        val id = dao.insertMemory(unpinned(text = "x", timestamp = 1L))

        dao.setMemoryPinned(id = id, isPinned = true)
        assertTrue(dao.getAllMemories().first { it.id == id }.isPinned)

        dao.setMemoryPinned(id = id, isPinned = false)
        assertFalse(dao.getAllMemories().first { it.id == id }.isPinned)
    }

    @Test
    fun updateMemory_replacesTextAndEmbeddingWithoutTouchingTimestamp() = runBlocking {
        val originalTimestamp = 42L
        val id = dao.insertMemory(
            MemoryChunkEntity(
                text = "before",
                embedding = "0.1,0.2",
                timestamp = originalTimestamp,
                isPinned = false,
            ),
        )

        dao.updateMemory(id = id, text = "after", embedding = "0.9,0.8")

        val updated = dao.getAllMemories().first { it.id == id }
        assertEquals("after", updated.text)
        assertEquals("0.9,0.8", updated.embedding)
        assertEquals(originalTimestamp, updated.timestamp)
        assertFalse(updated.isPinned)
    }

    @Test
    fun deleteMemoryById_removesSingleRow() = runBlocking {
        val keepId = dao.insertMemory(unpinned(text = "keep", timestamp = 1L))
        val dropId = dao.insertMemory(unpinned(text = "drop", timestamp = 2L))

        dao.deleteMemoryById(dropId)

        val survivors = dao.getAllMemories()
        assertEquals(1, survivors.size)
        assertEquals(keepId, survivors.single().id)
    }

    @Test
    fun deleteAllMemories_wipesPinnedAndUnpinned() = runBlocking {
        dao.insertMemory(unpinned(text = "u", timestamp = 1L))
        dao.insertMemory(pinned(text = "p", timestamp = 2L))

        dao.deleteAllMemories()

        assertTrue(dao.getAllMemories().isEmpty())
    }

    @Test
    fun getRecentMemorySummaries_projectsIdTextTimestampOnly() = runBlocking {
        val id = dao.insertMemory(
            MemoryChunkEntity(text = "hello", embedding = "1.0,2.0", timestamp = 5L, isPinned = false),
        )

        val summaries = dao.getRecentMemorySummaries(limit = 10)
        val summary = summaries.single()
        assertEquals(id, summary.id)
        assertEquals("hello", summary.text)
        assertEquals(5L, summary.timestamp)
    }

    @Test
    fun observeChunkCount_emitsLiveCount() = runBlocking {
        assertEquals(0, dao.observeChunkCount().first())

        dao.insertMemory(unpinned(text = "a", timestamp = 1L))
        assertEquals(1, dao.observeChunkCount().first())

        dao.insertMemory(unpinned(text = "b", timestamp = 2L))
        assertEquals(2, dao.observeChunkCount().first())

        dao.deleteAllMemories()
        assertEquals(0, dao.observeChunkCount().first())
    }

    @Test
    fun observeTotalBytes_sumsTextAndEmbeddingLengths() = runBlocking {
        assertEquals(0L, dao.observeTotalBytes().first())

        // `hello` (5) + `1.2,3.4` (7) = 12.
        dao.insertMemory(
            MemoryChunkEntity(text = "hello", embedding = "1.2,3.4", timestamp = 1L, isPinned = false),
        )
        assertEquals(12L, dao.observeTotalBytes().first())

        // Add `hi` (2) + empty embedding (0) → 12 + 2 = 14.
        dao.insertMemory(
            MemoryChunkEntity(text = "hi", embedding = "", timestamp = 2L, isPinned = false),
        )
        assertEquals(14L, dao.observeTotalBytes().first())
    }

    @Test
    fun getAllMemories_returnsEverythingIncludingPinned() = runBlocking {
        dao.insertMemory(unpinned(text = "u", timestamp = 1L))
        dao.insertMemory(pinned(text = "p", timestamp = 2L))

        val all = dao.getAllMemories()
        assertEquals(2, all.size)
        assertNotNull(all.firstOrNull { it.text == "u" })
        assertNotNull(all.firstOrNull { it.text == "p" })
        assertNull(all.firstOrNull { it.text == "missing" })
    }

    private fun unpinned(text: String, timestamp: Long): MemoryChunkEntity = MemoryChunkEntity(
        text = text,
        embedding = "0.0",
        timestamp = timestamp,
        isPinned = false,
    )

    private fun pinned(text: String, timestamp: Long): MemoryChunkEntity = MemoryChunkEntity(
        text = text,
        embedding = "0.0",
        timestamp = timestamp,
        isPinned = true,
    )
}
